### ISSUE TITLE
Ask for help. I'm puzzled with voc.py. Other operations may be required.

### ISSUE THREAD

**Issue by Iflier** [Hakuyume/chainer-ssd#1]
Hello!  @Hakuyume  Great jobs. Your work makes the world a better place. I have seen your project carefully. But, now I have some with the file voc.py. 
![default](https://cloud.githubusercontent.com/assets/19361364/23064734/bfedaca8-f54c-11e6-9fec-b73860cf5db7.PNG)
Just as the picture shows:  os.path.join(root, 'ImageSets', 'Main', name + '.txt'), after unzip VOCtrainval_06-Nov-2007.zip ,it's folder "Main" include many *.txt files, but in file voc.py, I guess 'name' should be in ['train', 'val','trainval'] or similar format. I'm a little confused here. It would be great if you can help me out. Thanks in advance..

**Comment by Hakuyume** [comment]
Thank you for your question.
As you guessed, `name` takes the name of subset, such as `train`, `val`, `trainval`, `test`.
My code retrieves the list of images from `{train, val, trainval, test}.txt`.
Other *.txt files in `Main` (aeroplane_test.txt, bicycle_train.txt, etc ...) are ignored.

**Comment by Iflier** [comment]
Great, thank you for your quick response!
