### ISSUE TITLE
VGGNet model download issue

### ISSUE THREAD

**Issue by np000** [Hakuyume/chainer-ssd#11]
seems the file in the URL is no longer available in the server (http://www.cs.unc.edu/~wliu/projects/SSD/)

http://www.cs.unc.edu/%7Ewliu/projects/SSD/models_VGGNet_VOC0712_SSD_300x300.tar.gz

**Comment by Hakuyume** [comment]
Please download from links in https://github.com/weiliu89/caffe/tree/ssd#models
