### ISSUE TITLE
Again, ask for help. Some problem with protobuf :DecodeError.

### ISSUE THREAD

**Issue by Iflier** [Hakuyume/chainer-ssd#2]
Hi, when I try to convert VGG_ILSVRC_16_layers_fc_reduced.caffemodel to vgg16.npz, some error occured:
on Win10 OS(Python 3.5.2, protobuf 3.2.0, chainer 1.21.0):
![win_err](https://cloud.githubusercontent.com/assets/19361364/23253302/fc90baa0-f9ee-11e6-9b90-b6ebce08543d.PNG)
and on Ubuntu 14.04 (python 3.4.3, protobuf 3.1.0, chainer 1.21.0):
![linux_err](https://cloud.githubusercontent.com/assets/19361364/23253409/5d8bfc48-f9ef-11e6-9ad1-c3df7df3e2ef.PNG).Now, I can not come up with the reason, so I ask for a hand from you. Thanks in advance .

**Comment by Hakuyume** [comment]
I updated `convert_caffe.py` recently and it seems that you are using old version.
Could you try again after updating your repository?
Also, please make sure `VGG_ILSVRC_16_layers_fc_reduced.caffemodel` is correctly downloaded
(the SHA256 digest is `bfc12099f68d3b71e781d8a7e2a5a11ea60839843f250cf64a5570906cd491f0`).

**Comment by Iflier** [comment]
Ok, I will have a try, right now. Many thanks.

**Comment by Iflier** [comment]
I'm sorry, I'm very sorry to ask such a stupid question and take up your time. After I downloaded the VGG_ILSVRC_16_layers_fc_reduced.caffemodel file again , everything goes well. Thanks again.
