### ISSUE TITLE
mAP code?

### ISSUE THREAD

**Issue by ellisbrown** [Hakuyume/chainer-ssd#3]
Where is your code to calculate mAP?  

The pascal provided code is in matlab, and it is frustrating that there are no good python implementation available anywhere.  I have been struggling to get a proper mAP for my pytorch implementation and am looking to check with someone else's.

Thanks

**Comment by Hakuyume** [comment]
I have no good mAP code. I used py-faster-rcnn (https://github.com/rbgirshick/py-faster-rcnn) to evaluate results (it was not easy to use, but better than MATLAB).
I am trying to implement better mAP code in python.

**Comment by Hakuyume** [comment]
We are developing a computer vision library, `ChainerCV`. It contains an evaluation code for PASCAL VOC.
https://github.com/pfnet/chainercv/blob/master/chainercv/evaluations/eval_detection_voc.py
