### ISSUE TITLE
Issue on Windows?

### ISSUE THREAD

**Issue by sitifukujin** [Hakuyume/chainer-ssd#4]
Hello Hakuyume-san,
On Windows and Python 3.6.0 :: Anaconda 4.3.0 (64-bit), This line occurs error.
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
multibox.py:56: 
hard_neg = rank < (np.count_nonzero(t_conf, axis=1) * 3)[:, np.newaxis]
TypeError: 'int' object is not subscriptable
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
I thought count_nonzero with axis does not work on windows.  
Output type is 'int' expected 'numpy'.
So I replaced source code like bellow and it seems working well.
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        non_zero = np.zeros((n,1))
        for i in range(n):
            non_zero[i] = (np.count_nonzero(t_conf[i])) 
        non_zero *= 3
        hard_neg = rank < non_zero
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Honestly saying, I have just started python for 2 month, so it is not beautiful.
But I like this chainer and SSD. I would like to contribute you. Please tell me how to do.
Thanks for your excellent always working.

**Comment by Hakuyume** [comment]
This is an issue on Anaconda. Anaconda is shipped with old `numpy`. In this version, `count_nonzero` does not have `axis` option.
I updated my source code to use `sum` instead of `count_nonzero`. It may work on Anaconda. Please try it.

**Comment by sitifukujin** [comment]
Perfect!! Thanks a lot.
