### ISSUE TITLE
demo.py for windows report

### ISSUE THREAD

**Issue by ghost** [Hakuyume/chainer-ssd#5]
In Windows, if not explicitly cast to float, it will be 0 and 'demo.py' will not work. work by this fix.
your code is very helpful. thank you!

class SSD300(chainer.Chain):
    ---------------------
    #steps = [s / 300 for s in (8, 16, 32, 64, 100, 300)]  ----- original code 
    steps = [np.float32(s) / 300 for s in (8, 16, 32, 64, 100, 300)] 
   #sizes = [np.float32(s) / 300 for s in (30, 60, 111, 162, 213, 264, 315)] ----- original code 
   sizes = [np.float32(s) / 300 for s in (30, 60, 111, 162, 213, 264, 315)]

**Comment by Hakuyume** [comment]
Thank you for your report. I guess you are using Python2. Is it right?
If so, you can fix this more simply by adding `from __future__ import division`.
(This article may help you. https://www.python.org/dev/peps/pep-0238/)

**Comment by ghost** [comment]
I confirmed that it works with your simple solution. Your solution is smart. It was helpful. Thank you!
