### ISSUE TITLE
wrong box point on display

### ISSUE THREAD

**Issue by shu11** [Hakuyume/chainer-ssd#6]
I try VGG_VOC0712Plus_SSD_512 model from [here](https://github.com/weiliu89/caffe/tree/ssd#models).

When I do demo.py, it displays wrong coordinates for dog. 

For example:

```shell
$ ./demo.py --arch 512 VGG_VOC0712Plus_SSD_512.npz VOCdevkit/VOC2007/JPEGImages/000001.jpg
```

result:

<img width="373" alt="2017-05-26 20 22 57" src="https://cloud.githubusercontent.com/assets/1924916/26492830/27ca18ba-4251-11e7-828d-944810d8679b.png">

Is this expected behavior?
I use python2.7, cuda-8.0 and chainer 1.24.

Thanks in advance.

**Comment by Hakuyume** [comment]
`VGG_VOC0712_SSD_*` and `VGG_VOC0712Plus_SSD_*` have different network architectures. My implementation supports only `VGG_VOC0712_SSD_*`. Could you try `VGG_VOC0712_SSD_512x512`?

**Comment by shu11** [comment]
@Hakuyume  Thank you for your replay.

I tried `VGG_VOC0712_SSD_512x512`, but I could not get good results.
I create the model file:
```shell
$ ./caffe2npz.py models/VGGNet/VOC0712/SSD_512x512/VGG_VOC0712_SSD_512x512_iter_120000.caffemodel VGG_VOC0712_SSD_512.npz
```

And the results are below:

```shell
$ ./demo.py --arch 512 VGG_VOC0712_SSD_512.npz VOCdevkit/VOC2007/JPEGImages/000001.jpg
```
<img width="307" alt="2017-05-29 17 10 10" src="https://cloud.githubusercontent.com/assets/1924916/26541691/b856af6e-4491-11e7-982e-07100419d980.png">

```shell
$ ./demo.py --arch 512 VGG_VOC0712_SSD_512.npz VOCdevkit/VOC2007/JPEGImages/000002.jpg
```
<img width="295" alt="2017-05-29 17 11 03" src="https://cloud.githubusercontent.com/assets/1924916/26541736/eb814174-4491-11e7-808a-3d4674028628.png">

```shell
$ ./demo.py --arch 512 VGG_VOC0712_SSD_512.npz VOCdevkit/VOC2007/JPEGImages/000003.jpg
```
<img width="550" alt="2017-05-29 17 11 43" src="https://cloud.githubusercontent.com/assets/1924916/26541744/f5b1f88c-4491-11e7-93f0-2a5a926e7968.png">

```shell
$ ./demo.py --arch 512 VGG_VOC0712_SSD_512.npz VOCdevkit/VOC2007/JPEGImages/000004.jpg
```
<img width="570" alt="2017-05-29 17 11 23" src="https://cloud.githubusercontent.com/assets/1924916/26541753/fe55dc6a-4491-11e7-8e2e-555f8b0cea0b.png">

**Comment by Hakuyume** [comment]
Could you try to add `from __future__ import division` at the top of `lib/ssd.py`?
https://github.com/Hakuyume/chainer-ssd/issues/5#issuecomment-297040461

**Comment by shu11** [comment]
Wow!

It's good solution for me. I could get the same result described in the README.

Thank you for your support. I deeply appreciate it.
